Workflow improvements
Workflow fix

Initial RPM test

Translation fixes

RPM fix

Initial DEB test

RPM fix

Update deb.yml

Update rpm.yml

Workflow update

Update build_gde.yml

Update build_gde.yml

Update build_gde.yml

diff --git a/.github/workflows/appimage.yml b/.github/workflows/appimage.yml
--- a/.github/workflows/appimage.yml
+++ b/.github/workflows/appimage.yml
@@ -1,4 +1,4 @@
-name: 2 | AppImage
+name: 02 | AppImage
 
 on:
   workflow_call:
@@ -9,24 +9,28 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: 'Version'
+        description: Version
         type: string
-        default: 'v0.0'
+        default: v0.0
         
 env:
   GODOT_VERSION: 4.4.1
-  EXPORT_FOLDER: bin/linux_x86_64
+  EXPORT_FOLDER: libs/bin/linux_x86_64
   APP_NAME: gozen
   APPIMAGE_DIR: ${{ github.workspace }}/gozen.AppDir
+  ARTIFACT_NAME: ffmpeg_windows_x86_64
 
-run-name: 'Build GoZen AppImage: ${{ inputs.version }} by @${{ github.actor }}'
+run-name: 'AppImage version: ${{ inputs.version }} by @${{ github.actor }}'
 
 jobs:
   build-appimage:
-    name: 'Build GoZen AppImage'
+    name: Build GoZen AppImage
     runs-on: ubuntu-22.04
+    permissions:
+      actions: read
+      contents: read
     steps:
-      - name: 'Installing dependencies'
+      - name: Installing dependencies
         run: |
           sudo add-apt-repository ppa:git-core/ppa
           sudo apt update
@@ -36,18 +40,42 @@ jobs:
           binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu \
           libnuma-dev fuse libfuse2 desktop-file-utils patchelf
 
-      - name: 'Checkout submodules'
+      - name: Checkout submodules
         uses: actions/checkout@v4
         with:
           submodules: recursive
 
-      - name: 'Cache Godot'
+      - name: Get latest run ID for "Compile GDE"
+        id: get_ffmpeg_workflow_run_id
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          WORKFLOW_NAME="11 | Compile GDE"
+          LATEST_RUN_ID=$(gh run list --workflow "${WORKFLOW_NAME}" --json databaseId --jq '.[0].databaseId')
+
+          if [ -z "$LATEST_RUN_ID" ]; then
+            echo "Error: Could not find latest run ID for workflow '${WORKFLOW_NAME}'."
+            exit 1
+          fi
+
+          echo "Found latest run ID: $LATEST_RUN_ID"
+          echo "latest_run_id=$LATEST_RUN_ID" >> "$GITHUB_OUTPUT"
+
+      - name: Get GDE artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: linux_gde
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ steps.get_ffmpeg_workflow_run_id.outputs.latest_run_id }}
+          path: ./libs/bin/linux_x86_64
+
+      - name: Cache Godot
         uses: actions/cache@v4
         with:
           path: ~/.local/share/godot
           key: ${{ runner.os }}-ubuntu-godot-${{ env.GODOT_VERSION }}
 
-      - name: 'Prepare Godot'
+      - name: Prepare Godot
         run: |
           if [ ! -f Godot_v${{ env.GODOT_VERSION }}-stable.x86_64 ]; then
             echo "Downloading Godot editor ..."
@@ -70,34 +98,17 @@ jobs:
 
           sed -i 's|^config/version\s*=.*|config/version="${{ inputs.version }}"|' src/project.godot
 
-      - name: 'Compiling GDE GoZen Debug'
-        working-directory: ./libs
-        run: |
-          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH
-
-          python3 -c "import sys; sys.path.append('.'); from build_utils import build_ffmpeg; build_ffmpeg.compile_ffmpeg('linux', 'x86_64', 4)"
-
-          scons -j$(nproc) target=template_debug platform=linux arch=x86_64 -c
-          scons -j$(nproc) target=template_release platform=linux arch=x86_64 -c
-
-          scons -j$(nproc) target=template_debug platform=linux arch=x86_64 cache_dir=scons_linux_debug
-          scons -j$(nproc) target=template_release platform=linux arch=x86_64 cache_dir=scons_linux_release
-
-      - name: 'Export for Linux'
+      - name: Export for Linux
         working-directory: ./src
         run: |
           mkdir -p ../${{ env.EXPORT_FOLDER }}
           ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --import godot.project --headless --export-release Linux_x86_64 ../${{ env.EXPORT_FOLDER }}/${{ env.APP_NAME }}.x86_64
           ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --headless --export-release Linux_x86_64 ../${{ env.EXPORT_FOLDER }}/${{ env.APP_NAME }}.x86_64
 
-      - name: 'Copy extra libs'
-        run: |
-          cp libs/bin/linux_x86_64/*.s* ${{ env.EXPORT_FOLDER }}
-          echo "reading bin"
-          ls libs/bin/linux_x86_64
-          rm ${{ env.EXPORT_FOLDER }}/libgozen*debug*.so
+      - name: Removing debug gde
+        run: rm ${{ env.EXPORT_FOLDER }}/libgozen*debug*.so
 
-      - name: 'Create AppDir structure'
+      - name: Create AppDir structure
         run: |
           mkdir -p ${{ env.APPIMAGE_DIR }}/usr/bin
           mkdir -p ${{ env.APPIMAGE_DIR }}/usr/lib
@@ -106,7 +117,7 @@ jobs:
           mkdir -p ${{ env.APPIMAGE_DIR }}/usr/share/doc/${{ env.APP_NAME }}
           echo "AppDir structure created at ${{ env.APPIMAGE_DIR }}"
 
-      - name: 'Copy app files to AppDir'
+      - name: Copy app files to AppDir
         run : |
           cp ${{ env.EXPORT_FOLDER }}/${{ env.APP_NAME }}.x86_64 ${{ env.APPIMAGE_DIR }}/usr/bin/${{ env.APP_NAME }}
           cp ${{ env.EXPORT_FOLDER }}/libgozen*.so ${{ env.APPIMAGE_DIR }}/usr/lib/
@@ -124,7 +135,7 @@ jobs:
           desktop-file-validate ${{ env.APPIMAGE_DIR }}/${{ env.APP_NAME }}.desktop
           echo "Application files copied to AppDir."
 
-      - name: 'Create AppRun script'
+      - name: Create AppRun script
         run: |
           cat <<EOF > ${{ env.APPIMAGE_DIR }}/AppRun
           #!/bin/bash
@@ -139,13 +150,13 @@ jobs:
           chmod +x ${{ env.APPIMAGE_DIR }}/AppRun
           echo "AppRun script created."
 
-      - name: 'Download linuxdeploy'
+      - name: Download linuxdeploy
         run: |
           wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy
           chmod +x linuxdeploy
           echo "linuxdeploy downloaded."
 
-      - name: 'Bundle dependencies and create AppImage'
+      - name: Bundle dependencies and create AppImage
         run: |
           export LD_LIBRARY_PATH="${{ env.APPIMAGE_DIR }}/usr/lib:$LD_LIBRARY_PATH"
 
@@ -167,9 +178,10 @@ jobs:
           echo "AppImage created and renamed to: ${{ env.APP_NAME }}-${{ inputs.version }}-x86_64.AppImage"
           ls -l *.AppImage
 
-      - name: 'Upload AppImage Artifact'
+      - name: Upload AppImage Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: GoZen-Linux-AppImage-${{ inputs.version }}
+          name: GoZen_Linux_AppImage_${{ inputs.version }}
           path: ${{ env.APP_NAME }}-${{ inputs.version }}-x86_64.AppImage
           if-no-files-found: error # Fails the workflow if the AppImage isn't found
+
diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -1,5 +1,4 @@
-name: 1 | Linux
-
+name: 01 | Linux
 on:
   workflow_call:
     inputs:
@@ -9,22 +8,24 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: 'Version'
+        description: Version
         type: string
-        default: 'v0.0'
+        default: v0.0
         
 env:
   GODOT_VERSION: 4.4.1
-  EXPORT_FOLDER: bin/linux_x86_64
+  EXPORT_FOLDER: libs/bin/linux_x86_64
 
-run-name: 'Build GoZen debug for Linux version: ${{ inputs.version }} by @${{ github.actor }}'
-
+run-name: 'Linux version: ${{ inputs.version }} by @${{ github.actor }}'
 jobs:
-  build-gde-linux:
-    name: 'Build GoZen'
+  build-linux:
+    name: Build GoZen
     runs-on: ubuntu-22.04
+    permissions:
+      actions: read
+      contents: read
     steps:
-      - name: 'Installing dependencies'
+      - name: Installing dependencies
         run: |
           sudo add-apt-repository ppa:git-core/ppa
           sudo apt update
@@ -34,18 +35,42 @@ jobs:
           binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu \
           libnuma-dev fuse libfuse2 desktop-file-utils patchelf
 
-      - name: 'Checkout submodules'
+      - name: Checkout submodules
         uses: actions/checkout@v4
         with:
           submodules: recursive
 
-      - name: 'Cache Godot'
+      - name: Get latest run ID for "Compile GDE"
+        id: get_ffmpeg_workflow_run_id
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          WORKFLOW_NAME="11 | Compile GDE"
+          LATEST_RUN_ID=$(gh run list --workflow "${WORKFLOW_NAME}" --json databaseId --jq '.[0].databaseId')
+
+          if [ -z "$LATEST_RUN_ID" ]; then
+            echo "Error: Could not find latest run ID for workflow '${WORKFLOW_NAME}'."
+            exit 1
+          fi
+
+          echo "Found latest run ID: $LATEST_RUN_ID"
+          echo "latest_run_id=$LATEST_RUN_ID" >> "$GITHUB_OUTPUT"
+
+      - name: Get GDE artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: linux_gde
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ steps.get_ffmpeg_workflow_run_id.outputs.latest_run_id }}
+          path: ./libs/bin/linux_x86_64
+
+      - name: Cache Godot
         uses: actions/cache@v4
         with:
           path: ~/.local/share/godot
           key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}
 
-      - name: 'Prepare Godot'
+      - name: Prepare Godot
         run: |
           if [ ! -f Godot_v${{ env.GODOT_VERSION }}-stable.x86_64 ]; then
             echo "Downloading Godot editor ..."
@@ -68,41 +93,30 @@ jobs:
 
           sed -i 's|^config/version\s*=.*|config/version="${{ inputs.version }}"|' src/project.godot
 
-      - name: 'Compiling GDE GoZen Debug'
-        working-directory: ./libs
+      - name: Prepare folder
         run: |
-          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH
-
-          python3 -c "import sys; sys.path.append('.'); from build_utils import build_ffmpeg; build_ffmpeg.compile_ffmpeg('linux', 'x86_64', 4)"
-
-          scons -j$(nproc) target=template_debug platform=linux arch=x86_64
-          scons -j$(nproc) target=template_release platform=linux arch=x86_64
-
-      - name: 'Prepare folder'
-        run: |
-          mkdir -p ${{ env.EXPORT_FOLDER }}
           cp LICENSE ${{ env.EXPORT_FOLDER }}/LICENSE
           cp MANUAL.md ${{ env.EXPORT_FOLDER }}/MANUAL.md
 
-      - name: 'Export for Linux'
+      - name: Export for Linux
         working-directory: ./src
         run: |
           ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --import godot.project --headless --export-release Linux_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.x86_64
           ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --headless --export-release Linux_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.x86_64
 
-      - name: 'Copy extra libs'
-        run: |
-          echo "Copying libs"
-          cp libs/bin/linux_x86_64/*.s* ${{ env.EXPORT_FOLDER }}
-          rm ${{ env.EXPORT_FOLDER }}/libgozen*debug*.so
-
-      - name: 'Fix RPATH'
+      - name: Fix RPATH
         working-directory: ${{ env.EXPORT_FOLDER }}
         run: |
-          echo "Setting RPATH"
           find . -maxdepth 1 -name "*.so*" -exec sudo patchelf --set-rpath '$ORIGIN' {} \;
+          find . -maxdepth 1 -name "*.x86_64" -exec sudo patchelf --set-rpath '$ORIGIN' {} \;
 
-      - name: 'Upload Linux'
+      - name: Remove unnecessary libs
+        working-directory: ${{ env.EXPORT_FOLDER }}
+        run: |
+          rm *template_debug.*
+          rm *stdc++.so*
+
+      - name: Upload Linux
         uses: actions/upload-artifact@v4
         with:
           name: GoZen_Linux_x86_64_${{ inputs.version }}
diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -1,5 +1,4 @@
-name: 3 | Windows
-
+name: 05 | Windows
 on:
   workflow_call:
     inputs:
@@ -9,24 +8,18 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: 'Version'
+        description: Version
         type: string
-        default: 'v0.0'
-        
+        default: v0.0
+
 env:
   GODOT_VERSION: 4.4.1
-  EXPORT_FOLDER: bin/windows_x86_64
+  EXPORT_FOLDER: libs/bin/windows_x86_64
 
-run-name: 'Build GoZen for Windows version: ${{ inputs.version }} by @${{ github.actor }}'
-
+run-name: 'Windows version: ${{ inputs.version }} by @${{ github.actor }}'
 jobs:
-  build-deps:
-    name: 'Build Windows dependencies'
-    uses: ./.github/workflows/windows_deps.yml
-
   build-gozen-windows:
-    needs: ['build-deps']
-    name: 'Build GoZen'
+    name: Build GoZen
     runs-on: windows-latest
     defaults:
       run:
@@ -63,12 +56,43 @@ jobs:
             mingw-w64-ucrt-x86_64-cmake
             mingw-w64-ucrt-x86_64-autotools
 
-      - name: 'Checkout submodules'
+      - name: Checkout submodules
         uses: actions/checkout@v4
         with:
           submodules: recursive
 
-      - name: 'Prepare Godot'
+      - name: Get latest run ID for "Compile GDE"
+        id: get_ffmpeg_workflow_run_id
+        shell: bash
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          WORKFLOW_NAME="11 | Compile GDE"
+          LATEST_RUN_ID=$(gh run list --workflow "${WORKFLOW_NAME}" --json databaseId --jq '.[0].databaseId')
+
+          if [ -z "$LATEST_RUN_ID" ]; then
+            echo "Error: Could not find latest run ID for workflow '${WORKFLOW_NAME}'."
+            exit 1
+          fi
+
+          echo "Found latest run ID: $LATEST_RUN_ID"
+          echo "latest_run_id=$LATEST_RUN_ID" >> "$GITHUB_OUTPUT"
+
+      - name: Get GDE artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: windows_gde
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ steps.get_ffmpeg_workflow_run_id.outputs.latest_run_id }}
+          path: ./libs/bin/windows_x86_64
+
+      - name: Cache Godot
+        uses: actions/cache@v4
+        with:
+          path: ~/.local/share/godot
+          key: ${{ runner.os }}-windows-godot-${{ env.GODOT_VERSION }}
+
+      - name: Prepare Godot
         run: |
           if [ ! -f Godot_v${{ env.GODOT_VERSION }}-stable.x86_64 ]; then
             echo "Downloading Godot editor ..."
@@ -92,84 +116,18 @@ jobs:
 
           sed -i 's|^config/version\s*=.*|config/version="${{ inputs.version }}"|' src/project.godot
 
-      - name: Get x264
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_x264
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get x265
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_x265
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get aom
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_aom
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get svt_av1
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_svt_av1
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get vpx
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_vpx
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get opus
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_opus
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get ogg + vorbis
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_ogg_vorbis
-          path: libs/ffmpeg/bin_windows
-
-      - name: Get mp3lame
-        uses: actions/download-artifact@v4
-        with:
-          name: dep_win_mp3lame
-          path: libs/ffmpeg/bin_windows
-
-      - name: 'Compiling FFmpeg'
-        working-directory: ./libs
+      - name: Prepare folder
         run: |
-          echo $(nproc) | python3 -c "import sys; sys.path.append('.'); from build_utils import build_ffmpeg; build_ffmpeg.build_ffmpeg_windows('x86_64', 4, {})"
-          echo $(nproc) | python3 -c "import sys; sys.path.append('.'); from build_utils import build_ffmpeg; build_ffmpeg.copy_lib_files_windows('x86_64')"
-        
-      - name: 'Compiling GDE GoZen'
-        working-directory: ./libs
-        run: |
-          scons -j$(nproc) target=template_debug platform=windows arch=x86_64 use_static_cpp=yes use_mingw=yes
-          scons -j$(nproc) target=template_release platform=windows arch=x86_64 use_static_cpp=yes use_mingw=yes
-
-      - name: 'Prepare folder'
-        run: |
-          mkdir -p ${{ env.EXPORT_FOLDER }}
           cp LICENSE ${{ env.EXPORT_FOLDER }}/LICENSE
           cp MANUAL.md ${{ env.EXPORT_FOLDER }}/MANUAL.md
 
-      - name: 'Export for Windows'
+      - name: Export for Windows
         working-directory: ./src
         run: |
           ../Godot_v${{ env.GODOT_VERSION }}-stable_win64_console.exe --import godot.project --headless
           ../Godot_v${{ env.GODOT_VERSION }}-stable_win64_console.exe --headless --export-release Windows_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.exe
 
-      - name: 'Copy extra libs'
-        run: |
-          echo "Copying libs"
-          cp libs/bin/windows_x86_64/*.dll  ${{ env.EXPORT_FOLDER }}
-
-      - name: 'Upload Windows'
+      - name: Upload Windows
         uses: actions/upload-artifact@v4
         with:
           name: GoZen_Windows_x86_64_${{ inputs.version }}
