Build fix

diff --git a/.github/workflows/build_windows.yml b/.github/workflows/build_windows.yml
--- a/.github/workflows/build_windows.yml
+++ b/.github/workflows/build_windows.yml
@@ -17,7 +17,7 @@ env:
   
   EXPORT_FOLDER: bin/windows_x86_64
 
-run-name: 'Build GoZen debug for Windows version: ${{ inputs.version }} by @${{ github.actor }}'
+run-name: 'Build GoZen for Windows version: ${{ inputs.version }} by @${{ github.actor }}'
 
 jobs:
   build-gde-windows:
@@ -27,18 +27,97 @@ jobs:
       image: archlinux:latest
     steps:
       - name: 'Installing pacman dependencies'
-        run: pacman -Sy --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 mingw-w64-gcc mingw-w64-binutils ffmpeg aarch64-linux-gnu-binutils aarch64-linux-gnu-gcc nasm cmake pkgconf
+        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg aarch64-linux-gnu-binutils aarch64-linux-gnu-gcc nasm cmake pkgconf fakeroot debugedit sudo go which
 
-      - name: 'yay'
+      - name: 'Creating fake user install yay'
         working-directory: /tmp
         run: |
-          git clone --depth 1 https://aur.archlinux.org/yay.git
-          cd yay
-          makepkg -si --noconfirm --needed
+          useradd -m builder
+          echo "builder ALL=(ALL) NOPASSWD: /usr/bin/pacman" > /etc/sudoers.d/builder
+          chmod 0440 /etc/sudoers.d/builder
 
-      - name: 'Installing yay dependencies'
+          PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> /home/builder/.bash_profile
+          chown builder:builder /home/builder/.bash_profile
+
+          echo 'Installing yay AUR helper...'
+          su -l builder -c "
+            export PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\$PATH\"
+            git clone --depth 1 https://aur.archlinux.org/yay.git
+            cd yay
+            makepkg -si --noconfirm --needed
+          "
+          echo 'yay installation complete.'
+
+      - name: 'Install MinGW AUR packages as builder using yay'
         run: |
-          yay -S --noconfirm --needed mingw-w64-pkg-config mingw-w64-x265 mingw-w64-x264
+          su -l builder -c "
+            export PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\$PATH\"
+            echo 'Installing mingw-w64 AUR packages with yay...'
+            yay -S --noconfirm --needed \
+              mingw-w64-pkg-config \
+              mingw-w64-environment \
+              mingw-w64-l-smash \
+              mingw-w64-x264
+            # If you re-add these, uncomment them:
+            # mingw-w64-cmake \
+            # mingw-w64-x265
+            echo 'AUR package installation complete.'
+          "
+
+
+#      - name: 'Manually installing mingw w64 packages'
+#        working-directory: /home/builder
+#        run: |
+#          su -l builder -c "
+#            git clone --depth 1 https://aur.archlinux.org/mingw-w64-pkg-config.git &&
+#            cd mingw-w64-pkg-config &&
+#            makepkg -si --noconfirm --needed
+#
+#            mkdir -p ~/aur_builds && cd ~/aur_builds || exit 1;
+#
+#            cd /home/builder
+#            echo 'Installing AUR package: mingw-w64-environment'
+#            rm -rf mingw-w64-environment; # Clean up previous clone, if any
+#            # The git clone URL is correct
+#            if git clone --depth 1 https://aur.archlinux.org/mingw-w64-environment.git; then
+#              cd mingw-w64-environment || exit 1;
+#              makepkg -si --noconfirm --needed
+#            else
+#              echo 'Failed to clone mingw-w64-environment'
+#              exit 1
+#            fi
+#
+#            cd /home/builder
+#            mkdir -p ~/aur_builds && cd ~/aur_builds || exit 1;
+#
+#            cd /home/builder
+#            echo 'Installing AUR dependency: mingw-w64-l-smash'
+#            if [ ! -d mingw-w64-l-smash ]; then
+#              git clone --depth 1 https://aur.archlinux.org/mingw-w64-l-smash.git
+#            fi
+#            cd mingw-w64-l-smash && makepkg -si --noconfirm --needed && cd ..
+#      
+#            cd /home/builder
+#            echo 'Installing mingw-w64-x264'
+#            if [ ! -d mingw-w64-x264 ]; then
+#              git clone --depth 1 https://aur.archlinux.org/mingw-w64-x264.git
+#            fi
+#            cd mingw-w64-x264 && makepkg -si --noconfirm --needed
+#          "
+#
+#            cd /home/builder
+#            echo 'Installing AUR dependency: mingw-w64-cmake'
+#            if [ ! -d mingw-w64-cmake ]; then
+#              git clone --depth 1 https://aur.archlinux.org/mingw-w64-cmake.git
+#            fi
+#            cd mingw-w64-cmake && makepkg -si --noconfirm --needed && cd ..
+#      
+#            cd /home/builder
+#            echo 'Installing mingw-w64-x265'
+#            if [ ! -d mingw-w64-x265 ]; then
+#              git clone --depth 1 https://aur.archlinux.org/mingw-w64-x265.git
+#            fi
+#            cd mingw-w64-x265 && makepkg -si --noconfirm --needed
 
       - name: 'Checkout submodules'
         uses: actions/checkout@v4
@@ -98,16 +177,6 @@ jobs:
 
           sed -i 's|^config/version\s*=.*|config/version="${{ inputs.version }}"|' src/project.godot
 
-     # I tried my best but no x264 and x265 for Window users for now. Windows is a pain.
-     # - name: Build x264 for Windows
-     #   run: |
-     #     git clone --depth 1 https://code.videolan.org/videolan/x264.git
-     #     cd x264
-     #     ./configure --host=x86_64-w64-mingw32 --cross-prefix=x86_64-w64-mingw32- --prefix=/usr/x86_64-w64-mingw32 --enable-static --enable-shared
-     #     make -j$(nproc)
-     #     make install
-     #     cd ..
-
         # This step is needed so Godot can identify the classes.
       - name: 'Compiling GDE GoZen Debug (Linux)'
         working-directory: ./libs
@@ -123,7 +192,7 @@ jobs:
           python -c 'import sys; sys.path.append("."); import build; build.copy_lib_files_linux("x86_64")'
           scons -j$(nproc) target=template_debug platform=linux arch=x86_64 cache_dir=scons_linux_debug
 
-      - name: 'clean ffmpeg'
+      - name: 'Clean ffmpeg'
         working-directory: ./libs/ffmpeg
         run: |
           if [ -f ffmpeg/ffbuild/config.mak ]; then
@@ -153,8 +222,8 @@ jobs:
       - name: 'Export for Windows'
         working-directory: ./src
         run: |
-          ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --import godot.project --headless --export-debug Windows_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.exe
-          ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --headless --export-debug Windows_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.exe
+          ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --import godot.project --headless --export-release Windows_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.exe
+          ../Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --headless --export-release Windows_x86_64 ../${{ env.EXPORT_FOLDER }}/GoZen.exe
 
       - name: 'Copy extra libs'
         run: |
@@ -163,7 +232,7 @@ jobs:
       - name: 'Upload Windows'
         uses: actions/upload-artifact@v4
         with:
-          name: GoZen_Windows_x86_64_${{ inputs.version }}-DEBUG
+          name: GoZen_Windows_x86_64_${{ inputs.version }}
           path: ${{ env.EXPORT_FOLDER }}
           retention-days: 2
 
